# https://taskfile.dev

version: '3'

vars:
  IMAGE: cookieshake/pyrami

tasks:
  default:
    deps: [build]

  build:
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t {{.IMAGE}}:latest .
  
  push:
    deps: [build]
    cmds:
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t {{.IMAGE}}:latest .

